version: '3.8'

services:
  web:
    image: mboxfront:1.0  
    ports:
      - "8000:8000"
    env_file:
      - .env  
    volumes:
      - /home/jose/Source/MediaBox/FaceBox/faces:/mbox/thumbnails  # Mount external file
    command: gunicorn facebox_api.wsgi:application --bind 0.0.0.0:8000

