services:
  web:
    image: mboxfront:1.0.5  
    container_name: mboxfront_1_0_5
    ports:
      - "8000:8000"
    env_file:
      - .env  
    volumes:
      - /home/jose/Source/MediaBox/FaceBox/faces:/mbox/thumbnails  # Mount external file
      - /home/jose/Source/MediaBox/logs:/mbox/logs
    command: gunicorn facebox_api.wsgi:application --bind 0.0.0.0:8000 --workers 1
